%include "lib/terminal/text.asm"
%include "lib/terminal/ascii.asm"
%include "lib/terminal/reset.asm"
%include "lib/terminal/command_buffer.asm"
%include "lib/terminal/read_command.asm"
%include "lib/terminal/main.asm"
