%include "lib/std_functions/print.asm"
%include "lib/std_functions/readchar.asm"
%include "lib/std_functions/check_in_range.asm"
%include "lib/std_functions/check_if_equal.asm"
%include "lib/std_functions/read_from_drive.asm"
